### PR TITLE
Gaddis-Gnielinski Pressure Drop Model

### PR DESCRIPTION
**Pull request by Jhaefner**

### CODE REVIEW

**Comment by lcarasik** [comment]
The density units do not seem to be consistent with the other script based off Zu. Can you check this and make sure?

**Comment by Jhaefner** [comment]
Yes, after I have a meeting in about 15 min I'll come back and update the Zu model to have the same units. I have it saved just have to upload it

**Comment by lcarasik** [comment]
I would encourage you to check this one specifically. The usage of density in g/cm3 with a velocity in m/s and physical dimensions in meters isn't consistent in this specific script. It doesn't look like density and velocity are used specifically till the last two lines for calculating pressure drop. 

It's good to check both, but I'm concerned the units do not match up internally to this addition.

**Comment by Jhaefner** [comment]
There's an implicit conversion to kPa instead of Pa which accounts for the g/cm3. But I will double check .

**Comment by lcarasik** [comment]
I would rather the conversion be explicit and done later in the script. This will prevent confusion in the future.

**Pull request merged**
